# site settings
title: ELENA
subtitle: KULAKOVA
email: kulakovaelena15@gmail.com
description:  I am Junior iOS Developer and this is my portfolio. I have Bachelor's Degree in Marketing and Management but I decided to change my career and graduated Udacity's Nanodegree for iOS development.
baseurl: #"/forty-jekyll-theme" # the subpath of your site, e.g. /blog
#url: / # the base hostname & protocol for your site
author: Elena Kulakova
street_address: Ekholmsvägen 301
city: Stockholm
#state:
zip_code: 127 51
country: Sweden
phone: +46 72 001 24 45

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
#instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
